# spell-checker: disable
---
version: '3'

tasks:
  release:patch:
    cmds:
      - task: release:tag
        vars:
          RELEASE_TYPE: patch
      - task: release:image

  release:minor:
    cmds:
      - task: release:tag
        vars:
          RELEASE_TYPE: minor
      - task: release:image

  release:major:
    cmds:
      - task: release:tag
        vars:
          RELEASE_TYPE: major
      - task: release:image

  release:tag:
    vars:
      RELEASE_TYPE: '{{default "patch" .RELEASE_TYPE}}'
    preconditions:
      - git diff --quiet --exit-code && git diff --quiet --exit-code --cached
    cmds:
      - 'npm version {{.RELEASE_TYPE}} -m ":bookmark: v%s"'
      - git push origin main --follow-tags

  release:image:
    vars:
      VERSION:
        sh: jq -r '.version' package.json
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
    cmds:
      - task: docker:build
        vars:
          TAGS: 'latest,{{.VERSION}},{{.COMMIT_HASH}}'
      - docker push ghcr.io/844196/magpie:latest
      - docker push ghcr.io/844196/magpie:{{.VERSION}}
      - docker push ghcr.io/844196/magpie:{{.COMMIT_HASH}}

  docker:build:
    vars:
      TAGS: '{{default "latest" .TAGS}}'
    cmd: |
      docker build . \
        --label 'org.opencontainers.image.source=https://github.com/844196/magpie' \
        --label 'org.opencontainers.image.licenses=ISC' \
        {{range $tag := splitList "," (default "" .TAGS)}}{{if $tag}}--tag ghcr.io/844196/magpie:{{$tag}}{{end}} {{end}}

  lint:
    deps:
      - lint:type
      - lint:format
      - lint:rule

  lint:type:
    cmd: npx tsc --noEmit

  lint:format:
    cmd: npx prettier --check .

  lint:rule:
    cmd: npx eslint .

  clean:
    cmd: find .generated -mindepth 1 -not -name .gitignore -delete
    ignore_error: true
