name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  actions: write # For delete actions cache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: /tmp/image-cache
          key: ${{ runner.os }}-magpie-workspace-cache-${{ github.event_name == 'push' && github.ref_name || github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-magpie-workspace-cache-main
            ${{ runner.os }}-magpie-workspace-cache-
            ${{ runner.os }}-

      - name: Restore cache
        if: ${{ steps.cache.outputs.cache-hit }}
        run: |
          docker load --input /tmp/image-cache/magpie_workspace.tar

      - name: Setup environment variables
        run: |
          echo "HOST_UID=$(id -u)" >> .env
          echo "HOST_GID=$(id -g)" >> .env

      - name: Run test
        uses: devcontainers/ci@v0.3
        with:
          imageName: magpie_workspace
          cacheFrom: magpie_workspace:latest
          imageTag: latest
          push: never
          runCmd: |
            set -euo pipefail
            task setup
            task lint

      - name: Store cache
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir -p /tmp/image-cache
          docker save --output /tmp/image-cache/magpie_workspace.tar magpie_workspace:latest

      - name: Delete previous cache
        if: ${{ github.event_name == 'push' && steps.cache.outputs.cache-hit }}
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete --confirm "${{ runner.os }}-magpie-workspace-cache-${{ github.ref_name }}"

      - name: Upload cache
        if: ${{ github.event_name == 'push' }}
        uses: actions/cache/save@v3
        with:
          path: /tmp/image-cache
          key: ${{ runner.os }}-magpie-workspace-cache-${{ github.ref_name }}
