name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment variables
        run: |
          echo "HOST_UID=$(id -u)" >> .env
          echo "HOST_GID=$(id -g)" >> .env
      - name: Lint
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            set -euo pipefail
            task setup lint
